Attempt to merge DAT AWS SSH functions.

diff --git a/functions/ssh b/functions/ssh
--- a/functions/ssh
+++ b/functions/ssh
@@ -1,5 +1,10 @@
 #!/bin/zsh
 #
+
+test1() {
+  echo "IN here"
+}
+
 ssh() {
   if [ "$(ps -p $(ps -p $$ -o ppid=) -o comm=)" = "tmux" ]; then
     tmux rename-window "$(echo $* | cut -d . -f 1)"
@@ -9,3 +14,86 @@ ssh() {
     command ssh "$@"
   fi
 }
+
+ssh-dat-qa() {
+  _ssh_dat dat-qa us-west-2 "$1"
+}
+
+_ssh_dat() {
+  local server
+  server=$(choose-dat-server "$1" "$2" linux $3) || return $?
+  
+  local instance_name
+  local keypair_name
+  local private_ip
+  local instance_id
+  read instance_name keypair_name private_ip instance_id <<< $(echo "$server")
+
+  echo -e "Connecting to: $instance_name at IP $private_ip with keypair $keypair_name"
+
+  if [[ "$keypair_name" = "DATProdKeyPair" ]]; then
+    read -p "
+It appears that you're trying to connect to production, type YES to continue: " connect_to_prod
+    if [[ "$connect_to_prod" != "YES" ]]; then
+      echo "Cancelled"
+      return 0
+    fi
+  fi
+
+  ssh -o StrictHostKeyChecking=no -i $AWS_KEYPAIR_DIR/$keypair_name.pem ec2-user@private_ip
+}
+
+list-aws-servers() {
+  local profile="$1"
+  local region="$2"
+
+  local instance_filter="?State.Name==`running` && Tags[?Key==`OS` && Value==`'"$3"'`]"
+
+  local query='
+    Reservations[*]
+    .Instances['"$instance_filter"']
+    .[Tags[?Key==`Name`] | [0].Value, KeyName, PrivateIpAddress, InstanceId, Tags[?Key==`OS`] | [0].Value]
+  '
+  local output=$(aws aws ec2 describe-instances --query "$query" --profile "$profile" --region "$region" --output text)
+
+  if [[ -n "$4" ]]; then
+    output=$(echo "$output" | grep "$4")
+  fi
+  echo "$output" | column -t | sort
+}
+
+select_from_list() {
+  IFS=$'\n'
+  local inpput_list=($(echo "$1"))
+  unset IFS
+
+  local index=1
+  local temp=""
+  local str
+  for i in "${input_list[@]}"; do
+    str=$(printf "%5s" "[$index]")
+    temp="$temp$str $i
+"
+    index=$(($index +1))
+  done
+
+  read -p "$temp
+$2: " index
+
+  if [[ ! "$index" =~ ^[0-9]+$ ]]; then
+    echo "Invalid selection, please enter a number" >&2
+    return 1
+  fi
+
+  index=$(($index - 1))
+  local input_list_size=${#input_list[@]}
+
+  if [[ $index -ge $input_list_size ]] || [[ $index -lt 0 ]]; then
+    echo "Invalid selection" >&2
+  fi
+
+  local selected_list_item=${input_list[$index]}
+  echo "$selected_list_item"
+}
+
+export -f select_from_list
